<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	/**
	 * Find a user by email or username
	 *
	 * @param	string	$identifier
	 * @author  Joseph Wynn <joseph@wildlyinaccurate.com>
	 */
	public function findUser($identifier)
	{
		$user = $this->_em->createQuery('SELECT u FROM Entity\User u WHERE u.email LIKE :identifier OR u.username LIKE :identifier')
			->setParameter('identifier', $identifier)
			->getResult();

		return (empty($user)) ? null : $user[0];
	}

}
