<?php

namespace Entity;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	/**
	 * Find a user by email or username
	 *
	 * @param	string	$identifier
	 * @author  Joseph Wynn <joseph@wildlyinaccurate.com>
	 */
	public function findUser($identifier)
	{
		$user = $this->_em->createQuery('SELECT u FROM Entity\User u WHERE u.email LIKE :identifier OR u.username LIKE :identifier')
			->setParameter('identifier', $identifier)
			->getResult();

		return (empty($user)) ? null : $user[0];
	}

	/**
	 * Get all Users
	 *
	 * @param	int		$offset
	 * @param	int		$entries_per_page
	 * @param	string	$search
	 * @return	array
	 */
	public function getAllUsers($offset, $entries_per_page)
	{
		$query_builder = $this->_em->createQueryBuilder();
		$query_builder->select('u')
			->from('Entity\User', 'u')
			->addOrderBy('u.username', 'DESC')
			->setFirstResult($offset)
			->setMaxResults($entries_per_page);

		$query = $query_builder->getQuery();

		return new Paginator($query);
	}

}
