<?php

namespace Entity\Proxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Country extends \Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getIso()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["iso"];
        }
        $this->__load();
        return parent::getIso();
    }

    public function getPrintableName()
    {
        $this->__load();
        return parent::getPrintableName();
    }

    public function getIso3()
    {
        $this->__load();
        return parent::getIso3();
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setPrintableName($printableName)
    {
        $this->__load();
        return parent::setPrintableName($printableName);
    }

    public function setIso3($iso3)
    {
        $this->__load();
        return parent::setIso3($iso3);
    }

    public function addUser(\Entity\User $user)
    {
        $this->__load();
        return parent::addUser($user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'iso', 'name', 'printableName', 'iso3', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}